name: oprx-or_core

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync]

permissions:
  contents: write

jobs:
  build:
    name: openwrt_core - [${{ matrix.target }}]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        target:
          #- aarch64_generic
          #- arm_cortex-a9
          #- armsr-armv8
          - x86_64

    steps:
    - name: Checkout
      continue-on-error: true
      uses: actions/checkout@main
      with:
        ref: ${{ matrix.target }}

    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        if [ "${{ matrix.target }}" = "aarch64_generic" ]; then
          echo "target=aarch64-6.12" >> "$GITHUB_ENV"
        elif [ "${{ matrix.target }}" = "arm_cortex-a9" ]; then
          echo "target=bcm53xx-6.12" >> "$GITHUB_ENV"
        elif [ "${{ matrix.target }}" = "armsr-armv8" ]; then
          echo "target=armv8-6.12" >> "$GITHUB_ENV"
        elif [ "${{ matrix.target }}" = "x86_64" ]; then
          echo "target=x86_64-6.6" >> "$GITHUB_ENV"
        fi

    - name: Sync kernel modules
      run: |
        kmod=$(curl -sk "https://api.github.com/repos/ilxp/oprx-builder/releases" | grep "browser_download_url" | grep "${{ env.target }}" | tail -1 | awk '{print $2}' | sed 's/\"//g')
        kmod_name=$(basename $kmod | sed 's/\.tar\.gz$//;s/^[^-]*-//')
        rm -rf $kmod_name
        curl -L $kmod -o $kmod_name.tar.gz --progress-bar
        tar zxf $kmod_name.tar.gz && rm -f $kmod_name.tar.gz
        echo "RELEASE_NAME=$kmod_name" >> "$GITHUB_ENV"
        echo $kmod_name

    - name: Git push
      continue-on-error: true
      run: |
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        [ -d .git ] && git init
        git add --all
        git commit -sm "${{ env.RELEASE_NAME }}"
        git push "https://${{ github.actor }}:${{ secrets.workflow_token }}@github.com/${{ github.repository }}" HEAD:${{ matrix.target }}

    - name: Delete old workflow runs
      env:
          GITHUB_TOKEN: ${{ secrets.workflow_token }}  # 使用 GitHub 提供的自动令牌
      run: |
          #!/bin/bash
          one_day_ago=$(date -d '1 day ago' +%Y-%m-%dT%H:%M:%SZ)
          repo="${GITHUB_REPOSITORY}"

          # 获取所有工作流运行记录
          runs=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/${repo}/actions/runs")

          # 遍历每个运行记录
          echo "$runs" | jq -c '.workflow_runs[]' | while read -r run; do
            created_at=$(echo "$run" | jq -r '.created_at')
            run_id=$(echo "$run" | jq -r '.id')

            # 检查运行记录是否在 1 天前
            if [[ "$created_at" < "$one_day_ago" ]]; then
              echo "Deleting run ID: $run_id created at $created_at"
              curl -X DELETE -H "Authorization: token ${GITHUB_TOKEN}" \
                "https://api.github.com/repos/${repo}/actions/runs/${run_id}"
            fi
          done
